Mini Recap: Numpy Array

In [1]:
import numpy as np
arr= np.array([1,2,3,4,5])
print(arr)
print(arr.shape)

[1 2 3 4 5]
(5,)


Practice Questions

Q1) Create a Numpy array containing numbers from 10 to 20

In [10]:
import numpy as np
arr= np.array([10,11,12,13,14,15,16,17,18,19,20])
print(arr)

[10 11 12 13 14 15 16 17 18 19 20]


This can also be done using Numpy's arange

In [13]:
import numpy as np
arr=np.arange(10,21)
print(arr)


[10 11 12 13 14 15 16 17 18 19 20]


Q2) Array Operations

If 
a = np.array([1,2,3])
b= np.array([4,5,6])

What will be the result of a+b, a*b

In [18]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)
print(a*b)
c=[1,2,3]
d=[4,5,6]
print(c+d)
# print(c*d) # TypeError: can't multiply sequence by non-int of type 'list'

[5 7 9]
[ 4 10 18]
[1, 2, 3, 4, 5, 6]


Unlike Normal Python lists where a*2 would repeat the list, Numpy does the actual Math

In [19]:
#Q3. Slicing

arr = np.array([10, 20, 30, 40, 50])

In [24]:
# How do you extract the middle three numbers [20, 30, 40]?
slicearr= arr[1:4]
print(slicearr)

[20 30 40]


In [27]:
#Q4)) (3×3 matrix with numbers 1–9, then extract the 2nd row).
matr=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [28]:
print(matr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [29]:
print(matr[1]) # to fetch the second row

[4 5 6]


In [30]:
# This array can also be generated without typing the nnumbers manually
matrix= np.arange(1,10).reshape(3,3)
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
